export const topic = {
    ElemSelectionChanged: 'ElemSelectionChanged',
    ElemPropertyChanged: 'ElemPropertyChanged',
    ElemCreationRequested: 'ElemCreationRequested',
    ElemCreated: 'ElemCreated',
    ElemRemoved: 'ElemRemoved',
    ModelChanged: 'ModelChanged',
    SaveProject: 'SaveProject',
    SaveProjectCompleted: 'SaveProjectCompleted',
    SaveProjectFailed: 'SaveProjectFailed',
    GenerateProjectRequested: 'GenerateProjectRequested',
    GenerateProjectCompleted: 'GenerateProjectCompleted',
    GenerateProjectFailed: 'GenerateProjectFailed',
    NewProjectRequested: 'NewProjectRequested',
    NewProjectCompleted: 'NewProjectCompleted',
    NewProjectFailed: 'NewProjectFailed',
    FetchProjectsListRequested: 'FetchProjectsListRequested',
    FetchProjectsListCompleted: 'FetchProjectsListCompleted',
    FetchProjectsListFailed: 'FetchProjectsListFailed',
    PreviewProjectRequested: 'HandleProjectsRequested',
}
